### PR TITLE
Add pretty printing capability

### PR DESCRIPTION
**Pull request by stokesman**
These changes add the ability to pretty print the results of `json2php` and a unit test for such use cases.

Here's one place interest in this feature has been expressed: https://github.com/WordPress/wordpress-develop/pull/2252#issuecomment-1158117769

If you'd be open to merging this I'd be glad to update the docs as part of the PR. 

Quick example:
```js
const printer = json2php.make({linebreak:'\n', indent:'\t'})
printer({one: 3, two: 20, three: [9, 3, 2]})

/* result:
array(
	'one' => 3, 
	'two' => 20, 
	'set' => array(
		9, 
		3, 
		2
	)
)
*/
```

### CODE REVIEW

**Comment by daniel-zahariev** [comment]
Hi, @stokesman, this looks great!
I'll be able to review tomorrow and very likely merge.

**Comment by stokesman** [comment]
Thanks @daniel-zahariev! I just pushed 9442df4 to make it a little prettier.

**Comment by daniel-zahariev** [comment]
@stokesman, thank you for your contribution 🙏🏻
I had to do some clean up and was time constrained so went the easy route and did the changes in the code myself. 
Please, forgive me for that. I've added you to the list of contributors.

**Comment by stokesman** [comment]
All good, thanks for adding the feature!

**Pull request closed without merging**
